import { Video, User, Category } from '@/types';

export const mockUsers: User[] = [
  {
    id: '1',
    username: 'creator1',
    displayName: '创作者一号',
    avatar: '/avatars/user1.jpg',
    subscribers: 125000,
    bio: '专业视频制作人，专注于高质量内容创作',
    joinDate: '2022-01-15',
  },
  {
    id: '2',
    username: 'creator2',
    displayName: '影像大师',
    avatar: '/avatars/user2.jpg',
    subscribers: 89000,
    bio: '热爱电影和摄影的创作者',
    joinDate: '2021-08-22',
  },
  {
    id: '3',
    username: 'creator3',
    displayName: '生活记录者',
    avatar: '/avatars/user3.jpg',
    subscribers: 234000,
    bio: '记录生活中的美好瞬间',
    joinDate: '2020-12-10',
  },
];

export const mockVideos: Video[] = [
  {
    id: '1',
    title: '精彩瞬间集锦 - 2024年度最佳视频合集',
    description: '汇集了2024年最精彩的视频瞬间，包含各种主题和风格的内容，绝对让您大饱眼福。',
    thumbnail: '/thumbnails/video1.jpg',
    duration: '15:32',
    views: 125634,
    likes: 8934,
    dislikes: 123,
    uploadDate: '2024-08-01T10:30:00Z',
    uploader: mockUsers[0],
    tags: ['精彩', '合集', '2024', '最佳'],
    category: 'entertainment',
    quality: '4K',
    rating: 4.8,
  },
  {
    id: '2',
    title: '城市夜景延时摄影 - 霓虹闪烁的都市之美',
    description: '使用专业设备拍摄的城市夜景延时摄影，展现现代都市的繁华与美丽。',
    thumbnail: '/thumbnails/video2.jpg',
    duration: '08:45',
    views: 67891,
    likes: 5234,
    dislikes: 67,
    uploadDate: '2024-07-28T14:20:00Z',
    uploader: mockUsers[1],
    tags: ['延时摄影', '城市', '夜景', '摄影'],
    category: 'art',
    quality: '4K',
    rating: 4.6,
  },
  {
    id: '3',
    title: '美食制作教程 - 传统手工面条的制作过程',
    description: '详细展示传统手工面条的制作过程，从和面到拉面，每一个步骤都有详细讲解。',
    thumbnail: '/thumbnails/video3.jpg',
    duration: '12:18',
    views: 89234,
    likes: 6789,
    dislikes: 89,
    uploadDate: '2024-07-25T09:15:00Z',
    uploader: mockUsers[2],
    tags: ['美食', '教程', '手工', '面条'],
    category: 'cooking',
    quality: 'HD',
    rating: 4.9,
  },
  {
    id: '4',
    title: '自然风光 - 春日樱花盛开的美丽瞬间',
    description: '记录春日樱花盛开的美丽瞬间，感受大自然的魅力和生命的力量。',
    thumbnail: '/thumbnails/video4.jpg',
    duration: '06:22',
    views: 156789,
    likes: 12345,
    dislikes: 234,
    uploadDate: '2024-07-20T16:45:00Z',
    uploader: mockUsers[0],
    tags: ['自然', '樱花', '春天', '风光'],
    category: 'nature',
    quality: '4K',
    rating: 4.7,
  },
  {
    id: '5',
    title: '科技前沿 - AI技术在日常生活中的应用',
    description: '探讨人工智能技术在日常生活中的各种应用场景，展望未来科技发展趋势。',
    thumbnail: '/thumbnails/video5.jpg',
    duration: '18:30',
    views: 234567,
    likes: 18900,
    dislikes: 345,
    uploadDate: '2024-07-15T11:30:00Z',
    uploader: mockUsers[1],
    tags: ['科技', 'AI', '人工智能', '未来'],
    category: 'technology',
    quality: 'HD',
    rating: 4.5,
  },
  {
    id: '6',
    title: '音乐创作 - 现代电子音乐制作过程分享',
    description: '分享现代电子音乐的创作过程，从灵感来源到最终作品的完整制作流程。',
    thumbnail: '/thumbnails/video6.jpg',
    duration: '22:15',
    views: 98765,
    likes: 7890,
    dislikes: 123,
    uploadDate: '2024-07-10T13:20:00Z',
    uploader: mockUsers[2],
    tags: ['音乐', '创作', '电子音乐', '制作'],
    category: 'music',
    quality: 'HD',
    rating: 4.8,
  },
];

export const mockCategories: Category[] = [
  {
    id: 'entertainment',
    name: '娱乐',
    slug: 'entertainment',
    icon: '🎬',
    videoCount: 1234,
  },
  {
    id: 'art',
    name: '艺术',
    slug: 'art',
    icon: '🎨',
    videoCount: 567,
  },
  {
    id: 'cooking',
    name: '美食',
    slug: 'cooking',
    icon: '🍳',
    videoCount: 890,
  },
  {
    id: 'nature',
    name: '自然',
    slug: 'nature',
    icon: '🌿',
    videoCount: 456,
  },
  {
    id: 'technology',
    name: '科技',
    slug: 'technology',
    icon: '💻',
    videoCount: 678,
  },
  {
    id: 'music',
    name: '音乐',
    slug: 'music',
    icon: '🎵',
    videoCount: 789,
  },
  {
    id: 'sports',
    name: '体育',
    slug: 'sports',
    icon: '⚽',
    videoCount: 345,
  },
  {
    id: 'education',
    name: '教育',
    slug: 'education',
    icon: '📚',
    videoCount: 567,
  },
];

export const featuredVideos = mockVideos.slice(0, 3);
export const trendingVideos = mockVideos.slice(1, 5);
export const recentVideos = mockVideos.slice(2, 6);